//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ePOD_DBEntities1 : DbContext
    {
        public ePOD_DBEntities1()
            : base("name=ePOD_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<baseSM> baseSMS { get; set; }
        public virtual DbSet<dds_config> dds_config { get; set; }
        public virtual DbSet<SMSResponse> SMSResponses { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
    
        public virtual int User_Details_Insert(string userName, string email, string password, Nullable<int> status, Nullable<int> roleID)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("User_Details_Insert", userNameParameter, emailParameter, passwordParameter, statusParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<sms_count_per_month_Result> sms_count_per_month()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sms_count_per_month_Result>("sms_count_per_month");
        }
    
        public virtual ObjectResult<sms_whatsapp_count_per_day_Result> sms_whatsapp_count_per_day()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sms_whatsapp_count_per_day_Result>("sms_whatsapp_count_per_day");
        }
    }
}
