//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSResponse
    {
        public int Id { get; set; }
        public string code_b { get; set; }
        public Nullable<int> damaged { get; set; }
        public Nullable<int> caked { get; set; }
        public string complaints { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> sms_request_id { get; set; }
        public Nullable<int> missing { get; set; }
    }
}
