//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlogin
    {
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.Guid> salt { get; set; }
        public Nullable<int> roleID { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> status { get; set; }
    }
}
